language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements-dev.txt
  - pip install coveralls
  
script:
  - python -m pytest
  - flake8 pytrade
  - coverage run -m pytest

after_success:
  - coveralls
