language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements-dev.txt
  - pip install pytest-cov
  - pip install coveralls
  
script:
  - python -m pytest --cov=pytrade/
  - flake8 pytrade

after_success:
  - coveralls
