language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -U pip
  - python setup.py install              # install your package
  - pip install -r requirements-dev.txt  # install requirements
  - pip install coveralls
  
script:
  - python -m pytest
  - flake8 pytrade
  - coverage run -m pytest

after_success:
  - coveralls